#!/bin/bash

# GitHub CLI PR Review Guide

echo "GitHub CLI (gh) PR Review Guide"
echo "-----------------------------------"
echo ""
echo "Basic Usage:"
echo "  1. Check PRs and Checkout Branches"
echo "  2. Review PR Diffs"
echo "  3. Submit Review Results"
echo ""
echo "Key Commands and Shortcuts (Aliases):"
echo ""
echo "  gh status     (gs)        : Check status of all repositories"
echo "  gh pr status  (prs)       : Check PR status in the current repository"
echo "  gh pr list    (prl)       : List PRs in the current repository"
echo "  gh pr checkout <PR_number> (prco <PR_number>) : Checkout the branch of the specified PR"
echo "  gh pr view    (prv)       : View details of the PR"
echo "  gh pr diff -w (prd)       : View PR diff, ignoring whitespace changes"
echo "  gh pr review  (prr)       : Start PR review (comments, approval, etc.)"
echo "  gh pr review -a -b \"LGTM\" (prlgtm) : Approve the PR with a \"LGTM\" comment"
echo ""
echo "PR Review Workflow:"
echo "  1. Use prl to find the PR number to review"
echo "  2. Use prco <PR_number> to checkout the branch"
echo "  3. Use prv or prd to view the PR content and diff"
echo "  4. Use prr to add review comments or approve the PR"
echo ""
echo "For more information, refer to the gh command manual and online documentation."
echo "  gh --help"
echo "  https://cli.github.com/"
